name: scadnano
description: A web-based simplified implementation of cadnano (https://cadnano.org/).
# version: 0.0.1
#homepage: https://web.cs.ucdavis.edu/~doty/scadnano/
#author: David Doty <doty@ucdavis.edu>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  dnd: ^1.4.0
  color: ^2.1.1
  tuple: ^1.0.2
  quiver: ^2.0.1
  rxdart: ^0.19.0
  test: ^1.5.1+1
  meta: ^1.1.6
  path: ^1.6.2
  platform_detect: ^1.3.5
#  maybe: ^0.3.8
#  archive: ^2.0.5
#  react: ^4.5.0
#  angular: ^5.1.0
#  bloc: ^0.7.2
#  meta: ^1.1.6
#  w_flux: ^2.10.1

dev_dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^1.2.0
