name: Dart CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub.bat run build_runner test -- -p chrome test/reducer_test.dart
