name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Output working directory
      run: pwd
    - name: Output list of directories
      run: ls
    - name: Build
      run: pub run build_runner build
    - name: Run tests
      run: pub run build_runner test
